version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    groups:
      docker-runtime:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    groups:
      npm-runtime:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    groups:
      github-actions:
        patterns:
          - "*"
